// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43hx33TsWKoOql4QiZN4SJHZcmx3-lHk',
    appId: '1:991255241940:web:bd79e27eff49d8ad990741',
    messagingSenderId: '991255241940',
    projectId: 'staycation-97046',
    authDomain: 'staycation-97046.firebaseapp.com',
    storageBucket: 'staycation-97046.appspot.com',
    measurementId: 'G-6QDM34H7CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUe_Qu2MIuAxFigktxRMJt8akCrF6eeA',
    appId: '1:991255241940:android:0dec9775801e2e7e990741',
    messagingSenderId: '991255241940',
    projectId: 'staycation-97046',
    storageBucket: 'staycation-97046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgdzTk0WNZp2hYEKAacmgpyyDgEERTkHo',
    appId: '1:991255241940:ios:8da0a1a6a24f20e7990741',
    messagingSenderId: '991255241940',
    projectId: 'staycation-97046',
    storageBucket: 'staycation-97046.appspot.com',
    iosBundleId: 'com.example.staycationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgdzTk0WNZp2hYEKAacmgpyyDgEERTkHo',
    appId: '1:991255241940:ios:d5c7f73eed22281e990741',
    messagingSenderId: '991255241940',
    projectId: 'staycation-97046',
    storageBucket: 'staycation-97046.appspot.com',
    iosBundleId: 'com.example.staycationApp.RunnerTests',
  );
}
